add contractDto and contractMapper, view works with contractDto now
SergeiAf1/mobile_system pull request #16
Opened 2021-10-27 11:33 UTC by SergeiAf1

Add contractDto and contractMapper
View works with contractDto now

2021-10-29 12:36 UTC, shapuran requested changes

2021-10-29 12:36 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/ContractController.java
> +        model.addAttribute("tariffs", tariffService.getAllTariffs()
All calculations including streaming has to be in service not controller.

2021-10-29 13:13 UTC, SergeiAf1 commented on src/main/java/com/javaschool/mobile/controller/ContractController.java
> +        model.addAttribute("tariffs", tariffService.getAllTariffs()
With streams i only do mapping Collections entity  to Collection Dto.
You said what Mapping should be in Controller, not in Service.
So, there is nothing to change...

2021-10-29 13:59 UTC, SergeiAf1 commented on src/main/java/com/javaschool/mobile/controller/ContractController.java
> +        model.addAttribute("tariffs", tariffService.getAllTariffs()
Or you mean i should create new methods in Mapper   toEntityCollection()    and   toDtoCollection()  ?

2021-11-01 08:29 UTC, shapuran approved these changes

2021-11-01 11:42 UTC, merged