add Tariff and Contract Controllers, add one method to ContractDao
SergeiAf1/mobile_system pull request #7
Opened 2021-10-11 11:55 UTC by SergeiAf1

Add Tariff and Contract Controllers, add one method to ContractDao

2021-10-11 13:36 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/ContractController.java
> +    @GetMapping("/contract/{phoneNumber}")
By RESTFUL best practice should be "/contract**s**/..."

2021-10-11 13:36 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/MyController.java
> +    @GetMapping("/user/addresses/{id}")
should be "/users/{user_id}/addresses/{address_id}"

2021-10-11 13:36 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +public class TariffController {
The whole mapping in this controller is not RESTFUL-compliant. Please read about:
https://restfulapi.net/

2021-10-11 13:41 UTC, shapuran requested changes
Consider inline comments.

2021-10-11 14:24 UTC, SergeiAf1 commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +public class TariffController {
Ok, I got it and I'll fix.
But that is not a RESTfull app with public API. I don't provide it.
That is MVC, and some of links, like "/admin/saveTariff" i need for connecting jsp pages and for run controllers methods...

Or even in such a context i should follow RESTfull rules?

2021-10-12 09:59 UTC, shapuran requested changes

2021-10-12 09:59 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    @RequestMapping("/admins/update/tariffs")
URI is not RESTful compliant

2021-10-12 09:59 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    @RequestMapping("/admins/add/tariffs")
URI is not RESTful compliant

2021-10-12 09:59 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    @RequestMapping("/admin/save/tariffs")
URI is not RESTful compliant

2021-10-12 09:59 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    @RequestMapping("/delete/tariffs")
URI is not RESTful compliant

2021-10-12 09:59 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +public class TariffController {
All backend API's should be RESTful.

2021-10-13 09:53 UTC, shapuran requested changes

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/MyController.java
> +    @GetMapping("/users/tariffs/{tariff_id}")
What do you mean with /users/tariffs/{id} ? Get particular tariff for all users?
If so then mapping should be "/tariffs"

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/MyController.java
> +    public String getAllTariffs(@PathVariable int tariff_id, Model model){
I think method name should be getTariffById

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/MyController.java
> +    public String getAddress(@PathVariable int address_id, Model model){
You should specify user id here otherwise at looks like you get address from all users.

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    @DeleteMapping("/tariffs")
You've missed /{tariff_id} in the mapping otherwise you delete all tariffs.

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +    public String saveTariff(@ModelAttribute("tariff") Tariff tariff) {
This is not "save" operation but "create".

2021-10-13 09:53 UTC, shapuran commented on src/main/java/com/javaschool/mobile/controller/TariffController.java
> +@RequestMapping("/admins")
What is meaning of "/admins"? What is domain model here?

2021-10-15 13:11 UTC, closed without merging